name: biology_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.1
  shared_preferences: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
<<<<<<< HEAD
=======
    - assets/images/q_img/
>>>>>>> develop
    - assets/database.db

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Medium.ttf
        weight: 400
      - asset: fonts/Montserrat-Bold.ttf
        style: bold

